InternetShop/ToyShop.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToyShop.WebUI.Models
{
    public class PagingInfo
    {

        // Кол-во товаров
        public int TotalItems { get; set; }

        // Кол-во товаров на одной странице
        public int ItemsPerPage { get; set; }

        // Номер текущей страницы
        public int CurrentPage { get; set; }

        // Общее кол-во страниц
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

InternetShop/ToyShop.WebUI/Models/ToysListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ToyShop.Domain.Entities;

namespace ToyShop.WebUI.Models
{
    public class ToysListViewModel
    {
        public IEnumerable<Toy> Toys { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

InternetShop/ToyShop.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToyShop.Domain.Abstract;

namespace ToyShop.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IToyRepository repository;

        public NavController(IToyRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Toys
                .Select(toy => toy.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

InternetShop/ToyShop.WebUI/Controllers/ToyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToyShop.Domain.Abstract;
using ToyShop.Domain.Entities;
using ToyShop.WebUI.Models;
using ToyShop.Domain.Concrete;

namespace ToyShop.WebUI.Controllers
{
    public class ToyController : Controller
    {
        private IToyRepository toyRepository;
        public int pageSize = 2;
        public ToyController(IToyRepository Repository)
        {
            toyRepository = Repository;
        }
        public ViewResult List(string category, int page = 1)
        {
          ToysListViewModel model = new ToysListViewModel
          {
                Toys = toyRepository.Toys
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(toy => toy.ToyId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                    toyRepository.Toys.Count() :
                    toyRepository.Toys.Where(toy => toy.Category == category).Count()
                },
              CurrentCategory = category

          };

            return View(model);
        }
    }
}

InternetShop/ToyShop.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Домой", "List", "Toy", null,
    new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
{
    controller = "Toy",
    action = "List",
    category = link,
    page = 1
}, new
{
    @class = "btn btn-block btn-default btn-lg"
    + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
})
}

InternetShop/ToyShop.WebUI/Views/Shared/ToySummary.cshtml
@model ToyShop.Domain.Entities.Toy

    <div class="well">
        <h3>
            <strong>@Model.Name</strong>
            <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
        </h3>
        <span class="lead">@Model.Description</span>
    </div>

InternetShop/ToyShop.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">ToyStore - магазин мягких игрушек</a>
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>

InternetShop/ToyShop.WebUI/Views/Toy/List.cshtml
@using ToyShop.WebUI.Models
@using ToyShop.WebUI.HtmlHelpers
@model ToysListViewModel

@{
    ViewBag.Title = "Товары";
}

@foreach (var p in @Model.Toys)
{
    @Html.Partial("ToySummary", p)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List",
        new { page = x, category = Model.CurrentCategory }))
</div>